version: '3'
services:
  tracing:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-server
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"

  echo-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - JAEGER_AGENT_HOST=jaeger-server
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SERVICE_NAME=echo-proxy

  server1:
    container_name: server1
    build:
      context: .
      dockerfile: Dockerfile_server
    environment:
      - JAEGER_AGENT_HOST=jaeger-server
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SERVICE_NAME=echo-server1

  server2:
    container_name: server2
    build:
      context: .
      dockerfile: Dockerfile_server
    environment:
      - JAEGER_AGENT_HOST=jaeger-server
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SERVICE_NAME=echo-server2
